//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class gradeTable
    {
        public int gradeId { get; set; }
        public Nullable<int> stdnt { get; set; }
        public Nullable<int> less { get; set; }
        public Nullable<short> exam1 { get; set; }
        public Nullable<short> exam2 { get; set; }
        public Nullable<short> exam3 { get; set; }
        public Nullable<decimal> average { get; set; }
        public Nullable<bool> situation { get; set; }
    
        public virtual lessonTable lessonTable { get; set; }
        public virtual studentTable studentTable { get; set; }
    }
}
